### ISSUE TITLE
Underside of beds appears extremely dark

### ISSUE THREAD

**Issue by muzikbike** [CottonMC/ModelsUnlocked#5]
This is a lot darker than they should appear, from what I know of other such block models.

![2019-10-21_15 14 59](https://user-images.githubusercontent.com/52297970/67213791-905d4400-f416-11e9-9eef-3055fd7a1991.png)

**Comment by Juuxel** [comment]
Hm, I'm not sure what causes this.

**Comment by Juuxel** [comment]
Can't reproduce in 1.16.1.
