### ISSUE TITLE
Other blocks that could be made customizable

### ISSUE THREAD

**Issue by muzikbike** [CottonMC/ModelsUnlocked#7]
- Wall signs: Only the wood part. This would also eliminate the weird floating effect the wall sign has. Text would still use block entity rendering.
- Standing signs: Not sure how rotation would work. Text would still use block entity rendering. Could the models also be modified somewhat as to fix MC-28561 and MC-157547, or would this be out with the scope of the mod?
- Creeper and zombie heads
- Creeper and zombie wall heads
- Skeleton and wither skeleton skulls
- Skeleton and wither skeleton wall skulls
- Banners: Only the stand
- Wall banners: Only the section that attaches to the wall

The following I'm considerably less sure of:

- Chests, trapped chests and ender chests: maybe the only part using the block entity renderer would be the lid?
- Shulker boxes: use a regular cube model when closed, so faces can be culled, and then switch to the usual model when opened? Or does that defeat the purpose of the mod?
- Player heads and player wall heads: I don't know enough about how these work to be able to suggest much in regards to them
- Other blocks would include stuff like ender dragon heads and wall heads, the actual bell itself, enchantment table books, and end portals and gateways. I really don't know enough about these blocks to be able to effectively comment on them, but having them somehow be remodelable would come in handy to at least some people.

**Comment by Juuxel** [comment]
The simple skulls/heads are already being worked on. I don't think that adding support for changing animated models or static parts of BER models is a good idea though.

**Comment by Juuxel** [comment]
The animated models could work if #2 is implemented by sharing code between entity renderers and BERs.

**Comment by muzikbike** [comment]
Should I split this up into multiple tickets, one for each unique model or group of models, for easier tracking?

**Comment by muzikbike** [comment]
Closing this ticket since ModelsUnlocked is pretty much a discontinued project from the time being, and has been largely supplanted by EnhancedBlockEntities - feel free to reopen this if work continues
